---
title: "R Notebook To learn the Charts and Graphs in R"
output: html_notebook
---
Pie Chart

Syntax : pie(x, labels, radius, main, col, clockwise)
```{r}
# Create data for the graph.
x <- c(21, 62, 10, 53)
labels <- c("London", "New York", "Singapore", "Mumbai")

# Give the chart file a name.
png(file = "city.jpg")

# Plot the chart.
pie(x,labels)

# Save the file.
dev.off()
```

```{r}
# Plot the chart with title and rainbow color pallet.
pie(x, labels, main = "City pie chart", col = rainbow(length(x)))
```

```{r}
piepercent<- round(100*x/sum(x), 1)
pie(x, labels = piepercent, main = "City pie chart",col = rainbow(length(x)))
legend("topright", c("London","New York","Singapore","Mumbai"), cex = 0.8,
   fill = rainbow(length(x)))
```

```{r}
install.packages('plotrix')
library(plotrix)
# Plot the chart. 3D
x <-  c(21, 62, 10,53)
lbl <-  c("London","New York","Singapore","Mumbai")
pie3D(x,labels = lbl,explode = 0.1, main = "Pie Chart of Countries ")
```

Bar Chart

```{r}
# Syntax : barplot(H,xlab,ylab,main, names.arg,col)
# Create the data for the chart
H <- c(7,12,28,3,41)
barplot(H)
```
```{r}
# Create the data for the chart
H <- c(7,12,28,3,41)
M <- c("Mar","Apr","May","Jun","Jul")
# Plot the bar chart 
barplot(H,names.arg=M,xlab="Month",ylab="Revenue",col="blue",
main="Revenue chart",border="red")
```

Stacked Bar Chart

```{r}
# Create the input vectors.
colors = c("green","orange","brown")
months <- c("Mar","Apr","May","Jun","Jul")
regions <- c("East","West","North")

# Create the matrix of the values.
Values <- matrix(c(2,9,3,11,9,4,8,7,3,12,5,2,8,10,11), nrow = 3, ncol = 5, byrow = TRUE)

# Give the chart file a name
png(file = "barchart_stacked.png")

# Create the bar chart
barplot(Values, main = "total revenue", names.arg = months, xlab = "month", ylab = "revenue", col = colors)

# Add the legend to the chart
legend("topleft", regions, cex = 1.3, fill = colors)

# Save the file
dev.off()
```

